# 워크플로우 이름 정의.
name: Check PR Title

# 워크플로우가 실행될 조건 정의.
on:
  pull_request:
    types: [opened, synchronize]

# 워크플로우 실행될 작업 정의.
jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Call 'Check PR Lint' Action
        id: pr_lint_check
        run: npm run lint
        with:
          script: |
            const pattern = /^(|docs|feat|fix|refactor|style|test|chore)(\([^)]+\))?:.+/
            const title = context.payload.pull_request.title

            if (!pattern.test(title)) {
              core.setFailed('PR 제목이 컨벤션에 맞지 않습니다.')
            }
