# 워크플로우 이름 정의.
name: Check PR Lint

# 워크플로우가 실행될 조건 정의.
on:
  pull_request:
    types: [opened, synchronize]

# 워크플로우 실행될 작업 정의.
jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
      - name: Call 'Check PR Lint' Action
        id: pr_lint_check
        run: npm run lint
