# 워크플로우 이름 정의.
name: Check PR Lint

# 워크플로우 실행 조건 정의.
on:
  pull_request:
    types: [ opened, reopen, synchronize ]

# 워크플로우 실행될 작업 정의.
jobs:
  check_pr_lint:
    runs-on: ubuntu-latest
    env:
      BASE_BRANCH: ${{ github.base_ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Diff
        id: lint
        run: |
          npx eslint $(git diff --name-only --diff-filter=ACMR origin/${{ env.BASE_BRANCH }} | grep -E '^src/.*\.(js|ts|vue)$')
        continue-on-error: true
          
      - name: Save Code Linting Results
        if: steps.lint.outcome == 'failure'
        run: |
          git fetch origin $BASE_BRANCH:refs/remotes/origin/${{ env.BASE_BRANCH }}
          echo "Base branch is ${{ env.BASE_BRANCH }}
          npx eslint --output-file lint_report.json --format json $(git diff --name-only --diff-filter=ACMR origin/${{ env.BASE_BRANCH }} | grep -E '^src/.*\.(js|ts|vue)$')
        continue-on-error: true

      - name: Annotate Code Linting Results
        if: steps.lint.outcome == 'failure'
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: lint_report.json
