# 워크플로우 이름 정의.
name: Check PR Lint

# 워크플로우 실행 조건 정의.
on:
  pull_request:
    types: [ opened, reopen, synchronize ]

# 워크플로우 실행될 작업 정의.
jobs:
  check_pr_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Diff
        run: npm run lint-diff
        continue-on-error: true
          
      - name: Save Code Linting Results
        run: npm run lint:report

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: lint_report.json
