# 워크플로우 이름 정의.
name: Hello World

# 워크플로우 실행 조건 정의.
on:
  pull_request:
    types: [opened, reopened, edited, ready_for_review]

# 워크플로우 실행될 작업 정의.
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: "Hello World"
        uses: action-study/github-actions/notify_hello_word@main
